[package]
name = "decisions"
version = "0.1.0"
authors = ["Fungus Humungus <fungus.humungus@gmail.com>"]

[dependencies]
clap = "2.31"
csv = "1"
serde = "1"
serde_derive = "1"
rayon = "1.0.1"
itertools = "0.7.8"